name: Build and Test

on:
  push:
    branches: ["master"]
  pull_request:
    branches: ["master"]

env:
  NODE_ENV: ${{ vars.NODE_ENV }}
  PORT: ${{ vars.PORT }}
  DATABASE: ${{ secrets.DATABASE }}
  AUTH_URL: ${{ vars.AUTH_URL }}
  RATELIMIT_MAXCONNECTIONS: ${{ vars.RATELIMIT_MAXCONNECTIONS }}
  RATELIMIT_WINDOWMS: ${{ vars.RATELIMIT_WINDOWMS }}
  CORS_WHITELIST: ${{ vars.CORS_WHITELIST }}

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Install pnpm
        uses: pnpm/action-setup@v4
      - name: Use Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "lts/Krypton"
      - run: pnpm i --frozen-lockfile
      - run: pnpm build
      - run: |
          pnpm start &
          sleep 10
      - run: curl http://localhost:${{ env.PORT }}/healthcheck | grep running
